version: '3'

services:
  database:
    build:
      context: ./database
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
#
  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.8&charset=utf8
    volumes:
      - ../../Shop:/var/www
#
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../../Shop:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
       - php-fpm
    ports:
       - "80:80"
